### ISSUE TITLE
这个库功能跟aspects基本一样，只有api上有细微差点……建议写相关功能先调研一下相关的库，避免重复造轮子

### ISSUE THREAD

**Issue by 3677065** [larksuite/SDMagicHook#2]

**Comment by gsdios** [comment]
开源的目的就是为了将原理和细节公之于众，供有需要的开发者鉴别甄选。这个库和aspects唯一相似之处就是基于isa指针替换的思路，代码实现和api设计迥然不同。另外，SDMagicHook也解决了aspects未能解决的KVO冲突问题，详见https://mp.weixin.qq.com/s?__biz=MzI1MzYzMjE0MQ==&mid=2247486231&idx=1&sn=1c6584e9dcc3edf71c42cf396bcab051&chksm=e9d0c0f5dea749e34bf23de8259cbc7c868d3c8a6fc56c4366412dfb03eac8f037ee1d8668a1&token=1383088962&lang=zh_CN#rd

在开源这份代码之前我并未了解和使用过aspects，发表完https://mp.weixin.qq.com/s/wxigL1Clem1dR8Nkt8LLMw 这篇技术文章之后看到有些留言提到了aspects然后我去github大概看了一下基本思路都是基于类似kvo的isa替换，但是从api设计以及实现上也有明确的区别，我们通过以下示例简要介绍下：

假设有这样一个自定义类Test，在其内部定义了一个求和的方法，接收四个int类型的参数。
```objc
@implementation Test

- (int)sumWithA:(int)a b:(int)b c:(int)c d:(int)d {
    return a + b + c + d;
}

@end
```
现在要求将四个参数分别平方然后再求和。

使用aspects实现如下：

    Test *testObj = [Test new];
    [testObj aspect_hookSelector:@selector(sumWithA:b:c:d:) withOptions:AspectPositionBefore usingBlock:^(id<AspectInfo> info, int a, int b, int c, int d) {
        int aa = a * a;
        int bb = b * b;
        int cc = c * c;
        int dd = d * d;
        [info.originalInvocation setArgument:&aa atIndex:2];
        [info.originalInvocation setArgument:&bb atIndex:3];
        [info.originalInvocation setArgument:&cc atIndex:4];
        [info.originalInvocation setArgument:&dd atIndex:5];
    } error:NULL];

    int sum = [testObj sumWithA:1 b:2 c:3 d:4];
    NSLog(@">>>> %d", sum); // >>>> 30

使用SDMagicHook实现如下：

    Test *testObj = [Test new];
    [testObj hookMethod:@selector(sumWithA:b:c:d:) impBlock:^(typeof(testObj) this, int a, int b, int c, int d) {
        __block int res;
        [this callOriginalMethodInBlock:^{
            res = [this sumWithA:a * a b:b * b c:c * c d:d * d];
        }];
        return res;
    }];

    int sum = [testObj sumWithA:1 b:2 c:3 d:4];
    NSLog(@">>>> %d", sum); // >>>> 30
由以上demo可以看出：
1.aspects使用AspectOptions来决定自定义方法和原始方法的执行顺序；SDMagicHook使用callOriginalMethodInBlock来调用原始方法，可以将原始方法放在自定义逻辑的前、中、后任意位置执行，更加灵活方便。

2.aspects将原始方法封装在NSInvocation里面，如果想要修改`sumWithA:b:c:d:`的参数值需要调用`setArgument:atIndex:`方法来实现，api不够简洁友好；SDMagicHook只需在callOriginalMethodInBlock的block参数内部直接调用原始的`sumWithA:b:c:d:`方法传参即可，直观简便。

以上示例简要列举了SDMagicHook和Aspects的众多区别中的一项，欢迎仔细研究对比两个库的代码实现以及api设计再做进一步的探讨，我们欢迎任何做了充分调研对比之后的技术交流。
