### ISSUE TITLE
demo0 KVO crash

### ISSUE THREAD

**Issue by Rannie** [larksuite/SDMagicHook#4]
2020-04-02 16:32:15.932354+0800 SDHookDemo[43318:2582823] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x600000353240 of class CALayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x6000003480c0> (
<NSKeyValueObservance 0x600000db42d0: Observer: 0x600002737300, Key path: class, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000db4210>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3dcce __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b3b9b2 objc_exception_throw + 48
	2   Foundation                          0x00007fff258e2f73 NSKVODeallocate + 569
	3   QuartzCore                          0x00007fff2b4d1795 _ZN2CA5Layer16free_transactionEPNS_11TransactionE + 623
	4   QuartzCore                          0x00007fff2b44e514 _ZN2CA11Transaction6commitEv + 942
	5   QuartzCore                          0x00007fff2b44ed81 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	6   CoreFoundation                      0x00007fff23da1067 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	7   CoreFoundation                      0x00007fff23d9bb1e __CFRunLoopDoObservers + 430
	8   CoreFoundation                      0x00007fff23d9c06a __CFRunLoopRun + 1226
	9   CoreFoundation                      0x00007fff23d9b884 CFRunLoopRunSpecific + 404
	10  GraphicsServices                    0x00007fff38b5ac1a GSEventRunModal + 139
	11  UIKitCore                           0x00007fff48c19220 UIApplicationMain + 1605
	12  SDHookDemo                          0x000000010c1db86a main + 122
	13  libdyld.dylib                       0x00007fff519b910d start + 1
	14  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by gsdios** [comment]
我们看一下

**Comment by gsdios** [comment]
demo没有复现，目前应该只有在较低版本的iOS系统上忘记移除kvo监听会发生cras，不过这也说明了系统kvo的一些安全缺陷，不妨切换到SDMagicHook再试一下。

**Comment by gsdios** [comment]
已修复，可以拉取最新代码测试下。 @Rannie
