### ISSUE TITLE
代码应该在哪里编写

### ISSUE THREAD

**Issue by TLHorse** [larksuite/SDMagicHook#5]
请问hook代码应该写到哪里呢？难道是直接写到程序xcodeproj源代码里吗？

能不能在程序已经编译好的情况下，通过**动态库注入**的方法，实现hook？
如果通过**动态库注入**的方法，实现hook，那么能不能hook swift方法？
如果可以注入动态库，那这个动态库能不能直接用swift+sdmagichook编写？

**Comment by tanpengsccd** [comment]
只有继承NSObject 才有runtime，也才能hook。

**Comment by gsdios** [comment]
SDMagicHook的原理主要是利用运行时动态交换实例的isa指针方式来实现。isa指针指向的对象类存储了该实例可以响应的以消息机制派发的方法，SDMagicHook只对消息机制派发的方法起作用。swift里面的方法派发有静态派发、函数表派发和消息派发三种方式，纯swift编写的代码一般都以静态派发、函数表派发方式执行（UIKit系列的类目前还主要是OC的消息机制派发），显式声明dynamic的方法可以转换为消息派发。
