### ISSUE TITLE
这个是不是只能对已知的实例(或者说自己生成的实例)进行hook

### ISSUE THREAD

**Issue by panxiaoqin** [larksuite/SDMagicHook#6]
如果这个实例不能你生成的 甚至你都不知道会存在在什么对象里面 你只知道这个对象有那些方法 是不是就无法hook

**Comment by gsdios** [comment]
无需了解实例本身如何设计，只要知道某个实例的selector即可hook。

**Comment by panxiaoqin** [comment]
我这样写必定报错   

        let imp: @convention(block) (TestClass, Int32,Int32) -> Int32 = { (vc, a,b) in
            vc.callOriginalMethod {
                vc.sub(a, value: b)
            }
            return 10
        }
        
        let hookID = TestClass.hookMethod(#selector(TestClass.sub(_:value:)), impBlock: imp)
        let aaa = TestClass()
        let c = aaa.sub(1, value: 2)
        print(c)

必须改成   

        let hookID = aaa.hookMethod(#selector(TestClass.sub(_:value:)), impBlock: imp)

sub 不是静态方法

**Comment by gsdios** [comment]
TestClass.hookMethod() 表示是hook TestClass的类方法，在这里将TestClass看做一个类对象
aaa.hookMethod() 表示hook aaa这个实例拥有的实例方法
这正是实例维度hook的特点
