### ISSUE TITLE
swift 调用 请检查你是否在hook了 `pointInside:withEvent:` 方法之后忘记调用原始方法。

### ISSUE THREAD

**Issue by tanpengsccd** [larksuite/SDMagicHook#7]
`请检查你是否在hook了 `<ButtonDropdown: 0x12a019350; baseClass = UIButton; frame = (20 9.5; 57 20); opaque = NO; layer = <CALayer: 0x2807c1fc0>>` 的 `pointInside:withEvent:` 方法之后忘记调用原始方法。`

``` swift
    //扩大点击响应面积
    private func expandBtn(){
        let imp: @convention(block) (UIView , CGPoint , UIEvent ) -> Bool = { (v,p,e) in
            v.callOriginalMethod {
                v.point(inside: p, with: e) //这里为何一定要调用一次？，不调用就会 请检查你是否在hook了 `pointInside:withEvent:` 方法之后忘记调用原始方法。
            }
            let r = v.bounds.inset(by: .init(top: 10, left: 10, bottom: 10, right: 30))
            return r.contains(p)
        }
        self.btn_buiding.hookMethod(#selector(UIButton.point(inside:with:)), impBlock: imp)
//        self.btn_floor.hookMethod(#selector(UIButton.point(inside:with:)), impBlock: imp)
    }
```

**Comment by gsdios** [comment]
这个是SDMagicHook的调用链检查机制检测到你在进行hook操作之后没有调用原始方法报出的警告。
很多人在hook时候忘记调用hook之前的原始方法导致整个调用链断裂，然后影响了在你之前hook这同一个方法的其他人的代码导致他们的hook实现会被调用了，出现各种暗坑。
如果确定不需要调用原始方法或者想要屏蔽掉调用检查警告，可以按如下方式操作下：
/// debug模式下会自动检查hook操作是否忘记调用原始方法，如果发现未调用原始方法会暂停当前进程帮助你定位问题，
/// 如果你不希望在检测到异常时暂停当前进程请将此tag置为NO。
extern BOOL SDMagicHookDebugFlag;
