### ISSUE TITLE
hook方法后，不调用以前hook的方法崩溃

### ISSUE THREAD

**Issue by songhongkang** [larksuite/SDMagicHook#8]
能不崩溃吗，我hook方法后，以前的方法不需要执行

**Comment by gsdios** [comment]
不是崩溃了，强制暂停程序提醒你，点击“继续”调试按钮程序可以继续执行。
/// debug模式下会自动检查hook操作是否忘记调用原始方法，如果发现未调用原始方法会暂停当前进程帮助你定位问题，
/// 如果你不希望在检测到异常时暂停当前进程请将此tag置为NO。
extern BOOL SDMagicHookDebugFlag;

**Comment by songhongkang** [comment]
谢谢
