### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by mengshun** [larksuite/SDMagicHook#9]
我初次运行该项目时发现 在点击 DemoVC0 CatchIt 按钮后, 在点击方法中 hook 了layer 的setBackgroundColor 方法,  再次返回home, 然后就Crash.

看了代码发现 在SDMagicHook.h第 148行代码, 调用了 SDNewClassManager的hasSetupKVO属性 判定是否添加了 kvo,  如果没有添加KVO 则添加,  查看了整个项目 都没有发现有移出 该KVO 的代码, 所以导致的Crash.

不知道作者设计hasSetupKVO是否有其他的考量,
在SDMagicHook.h第 249行, 同样加入了KVO 监听 依然没有移出监听操作,
上述只是我在学习时发现的.

iOS版本: 14.0
复现情况: 必现

@gsdios

**Comment by mengshun** [comment]
移出相关KVO监听代码, Crash不再出现

**Comment by gsdios** [comment]
iOS 14应该需要适配下，我们看下。

1. 第148行是进行前置观察订阅操作，为后面的custom-kvo实现做准备，因为之前考虑观察者和被观察者几乎同一时刻销毁掉了，所以没有移除观察，在其他系统版本上测试没有问题，iOS 14上可能需要特殊处理下
2.第249行是hook了addObserver:forKeyPath:options:context:之后当addObserver:forKeyPath:options:context:被调用的时候来调用原始实现的操作

**Comment by gsdios** [comment]
layer比较特殊可能需要适配，先将demo中的layer换成view不影响demo演示，我们会尽快给出相关解决方案

**Comment by gsdios** [comment]
已修复，可以拉取最新代码测试下 @mengshun

**Comment by mengshun** [comment]
看到并验证了, Issue已修复, 作者很效率, 赞👍
